apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{JOB_NAME}}
spec:
  schedule: "{{SCHEDULE}}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{JOB_NAME}}
            image: {{IMAGE}}  
            command: ["node", "{{FILE_TO_RUN}}"]
            env: {{ENV_VARS}}
          restartPolicy: OnFailure
